/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProfileLazyImport = createFileRoute('/profile')()
const LoginLazyImport = createFileRoute('/login')()
const LibroSearchLazyImport = createFileRoute('/libroSearch')()
const CartLazyImport = createFileRoute('/cart')()
const AboutusLazyImport = createFileRoute('/aboutus')()

// Create/Update Routes

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const LibroSearchLazyRoute = LibroSearchLazyImport.update({
  id: '/libroSearch',
  path: '/libroSearch',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/libroSearch.lazy').then((d) => d.Route))

const CartLazyRoute = CartLazyImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cart.lazy').then((d) => d.Route))

const AboutusLazyRoute = AboutusLazyImport.update({
  id: '/aboutus',
  path: '/aboutus',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/aboutus.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aboutus': {
      id: '/aboutus'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof AboutusLazyImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartLazyImport
      parentRoute: typeof rootRoute
    }
    '/libroSearch': {
      id: '/libroSearch'
      path: '/libroSearch'
      fullPath: '/libroSearch'
      preLoaderRoute: typeof LibroSearchLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/aboutus': typeof AboutusLazyRoute
  '/cart': typeof CartLazyRoute
  '/libroSearch': typeof LibroSearchLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
}

export interface FileRoutesByTo {
  '/aboutus': typeof AboutusLazyRoute
  '/cart': typeof CartLazyRoute
  '/libroSearch': typeof LibroSearchLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/aboutus': typeof AboutusLazyRoute
  '/cart': typeof CartLazyRoute
  '/libroSearch': typeof LibroSearchLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/aboutus' | '/cart' | '/libroSearch' | '/login' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/aboutus' | '/cart' | '/libroSearch' | '/login' | '/profile'
  id: '__root__' | '/aboutus' | '/cart' | '/libroSearch' | '/login' | '/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutusLazyRoute: typeof AboutusLazyRoute
  CartLazyRoute: typeof CartLazyRoute
  LibroSearchLazyRoute: typeof LibroSearchLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutusLazyRoute: AboutusLazyRoute,
  CartLazyRoute: CartLazyRoute,
  LibroSearchLazyRoute: LibroSearchLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/aboutus",
        "/cart",
        "/libroSearch",
        "/login",
        "/profile"
      ]
    },
    "/aboutus": {
      "filePath": "aboutus.lazy.tsx"
    },
    "/cart": {
      "filePath": "cart.lazy.tsx"
    },
    "/libroSearch": {
      "filePath": "libroSearch.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/profile": {
      "filePath": "profile.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
