/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const PublicLazyImport = createFileRoute('/public')()
const ProfileLazyImport = createFileRoute('/profile')()
const OrdersLazyImport = createFileRoute('/orders')()
const LoginLazyImport = createFileRoute('/login')()
const ContactLazyImport = createFileRoute('/contact')()
const CartLazyImport = createFileRoute('/cart')()
const BookSearchLazyImport = createFileRoute('/bookSearch')()
const BookDetailLazyImport = createFileRoute('/bookDetail')()
const AboutusLazyImport = createFileRoute('/aboutus')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const PublicLazyRoute = PublicLazyImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/public.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const OrdersLazyRoute = OrdersLazyImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orders.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const ContactLazyRoute = ContactLazyImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))

const CartLazyRoute = CartLazyImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cart.lazy').then((d) => d.Route))

const BookSearchLazyRoute = BookSearchLazyImport.update({
  id: '/bookSearch',
  path: '/bookSearch',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bookSearch.lazy').then((d) => d.Route))

const BookDetailLazyRoute = BookDetailLazyImport.update({
  id: '/bookDetail',
  path: '/bookDetail',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bookDetail.lazy').then((d) => d.Route))

const AboutusLazyRoute = AboutusLazyImport.update({
  id: '/aboutus',
  path: '/aboutus',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/aboutus.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/aboutus': {
      id: '/aboutus'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof AboutusLazyImport
      parentRoute: typeof rootRoute
    }
    '/bookDetail': {
      id: '/bookDetail'
      path: '/bookDetail'
      fullPath: '/bookDetail'
      preLoaderRoute: typeof BookDetailLazyImport
      parentRoute: typeof rootRoute
    }
    '/bookSearch': {
      id: '/bookSearch'
      path: '/bookSearch'
      fullPath: '/bookSearch'
      preLoaderRoute: typeof BookSearchLazyImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/aboutus': typeof AboutusLazyRoute
  '/bookDetail': typeof BookDetailLazyRoute
  '/bookSearch': typeof BookSearchLazyRoute
  '/cart': typeof CartLazyRoute
  '/contact': typeof ContactLazyRoute
  '/login': typeof LoginLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/public': typeof PublicLazyRoute
  '/signup': typeof SignupLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/aboutus': typeof AboutusLazyRoute
  '/bookDetail': typeof BookDetailLazyRoute
  '/bookSearch': typeof BookSearchLazyRoute
  '/cart': typeof CartLazyRoute
  '/contact': typeof ContactLazyRoute
  '/login': typeof LoginLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/public': typeof PublicLazyRoute
  '/signup': typeof SignupLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/aboutus': typeof AboutusLazyRoute
  '/bookDetail': typeof BookDetailLazyRoute
  '/bookSearch': typeof BookSearchLazyRoute
  '/cart': typeof CartLazyRoute
  '/contact': typeof ContactLazyRoute
  '/login': typeof LoginLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/public': typeof PublicLazyRoute
  '/signup': typeof SignupLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutus'
    | '/bookDetail'
    | '/bookSearch'
    | '/cart'
    | '/contact'
    | '/login'
    | '/orders'
    | '/profile'
    | '/public'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutus'
    | '/bookDetail'
    | '/bookSearch'
    | '/cart'
    | '/contact'
    | '/login'
    | '/orders'
    | '/profile'
    | '/public'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/aboutus'
    | '/bookDetail'
    | '/bookSearch'
    | '/cart'
    | '/contact'
    | '/login'
    | '/orders'
    | '/profile'
    | '/public'
    | '/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutusLazyRoute: typeof AboutusLazyRoute
  BookDetailLazyRoute: typeof BookDetailLazyRoute
  BookSearchLazyRoute: typeof BookSearchLazyRoute
  CartLazyRoute: typeof CartLazyRoute
  ContactLazyRoute: typeof ContactLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  OrdersLazyRoute: typeof OrdersLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  PublicLazyRoute: typeof PublicLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutusLazyRoute: AboutusLazyRoute,
  BookDetailLazyRoute: BookDetailLazyRoute,
  BookSearchLazyRoute: BookSearchLazyRoute,
  CartLazyRoute: CartLazyRoute,
  ContactLazyRoute: ContactLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  OrdersLazyRoute: OrdersLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  PublicLazyRoute: PublicLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/aboutus",
        "/bookDetail",
        "/bookSearch",
        "/cart",
        "/contact",
        "/login",
        "/orders",
        "/profile",
        "/public",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/aboutus": {
      "filePath": "aboutus.lazy.tsx"
    },
    "/bookDetail": {
      "filePath": "bookDetail.lazy.tsx"
    },
    "/bookSearch": {
      "filePath": "bookSearch.lazy.tsx"
    },
    "/cart": {
      "filePath": "cart.lazy.tsx"
    },
    "/contact": {
      "filePath": "contact.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/orders": {
      "filePath": "orders.lazy.tsx"
    },
    "/profile": {
      "filePath": "profile.lazy.tsx"
    },
    "/public": {
      "filePath": "public.lazy.tsx"
    },
    "/signup": {
      "filePath": "signup.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
